version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    container_name: mysql-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_USER=root
      - MARIADB_DATABASE=laravel
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - 3306:3306
  myapp:
    tty: true
    image: docker.io/bitnami/laravel:7-debian-10
    container_name: app-server
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_DATABASE=laravel
      - DB_PASSWORD=123
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
